swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0

host: localhost:3000
basePath: /
schemes:
  - http

paths:
  /api/v1/posts:
    get:
      summary: Returns a list of posts.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
